// Generated by Atelier P5Generator
// Prompt: Test
// Seed: 729382622

function setup() {
  createCanvas(400, 400);
  background(220);
}

function draw() {
  fill(0);

  // Draw dynamic shapes based on time
  const time = millis() * 0.001;
  translate(width / 2, height / 2);

  for (let i = 0; i < 5; i++) {
    push();
    rotate(time * 0.5 + i * TWO_PI / 5);
    translate(50, 0);
    ellipse(0, 0, 32, 32);
    pop();
  }
}