export type MemoPriority = 'low' | 'medium' | 'high';
export type MemoVerdict = 'approve' | 'revise' | 'reject';

export interface EvaluationMemoSection {
  title: string;
  content: string;
  priority: MemoPriority;
}

export interface EvaluationMemo {
  id: string;
  title: string;
  brief: string;
  sections: EvaluationMemoSection[];
  finalVerdict: MemoVerdict;
  score: number;
  generatedBy: string;
  timestamp: string;
}

export interface EvaluationMemoSummary {
  totalEvaluations: number;
  approveRate: number;
  avgScore: number;
  commonIssues: string[];
}

export class EvaluationMemoBuilder {
  private title?: string;
  private brief?: string;
  private finalVerdict?: MemoVerdict;
  private score?: number;
  private generatedBy?: string;
  private readonly sections: EvaluationMemoSection[] = [];

  setTitle(title: string): this {
    this.title = title;
    return this;
  }

  setBrief(brief: string): this {
    this.brief = brief;
    return this;
  }

  addSection(title: string, content: string, priority: MemoPriority = 'medium'): this {
    this.sections.push({ title, content, priority });
    return this;
  }

  setVerdict(verdict: MemoVerdict, score: number): this {
    this.finalVerdict = verdict;
    this.score = score;
    return this;
  }

  setGeneratedBy(generatedBy: string): this {
    this.generatedBy = generatedBy;
    return this;
  }

  build(): EvaluationMemo {
    if (!this.title) throw new Error('EvaluationMemo requires a title');
    if (!this.brief) throw new Error('EvaluationMemo requires a brief');
    if (!this.finalVerdict) throw new Error('EvaluationMemo requires a verdict');
    if (this.score === undefined) throw new Error('EvaluationMemo requires a score');
    if (this.score < 0 || this.score > 1) throw new Error('EvaluationMemo score must be between 0 and 1');
    if (!this.generatedBy) throw new Error('EvaluationMemo requires a generatedBy value');

    return {
      id: `memo-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
      title: this.title,
      brief: this.brief,
      sections: [...this.sections],
      finalVerdict: this.finalVerdict,
      score: this.score,
      generatedBy: this.generatedBy,
      timestamp: new Date().toISOString(),
    };
  }
}

export function formatMemo(memo: EvaluationMemo): string {
  const sections = memo.sections
    .map((section) => `## ${section.title}\n\nPriority: ${section.priority}\n\n${section.content}`)
    .join('\n\n');
  return [
    `# ${memo.title}`,
    memo.brief,
    `Verdict: ${memo.finalVerdict.toUpperCase()}`,
    `Score: ${memo.score.toFixed(2)}`,
    `Generated by: ${memo.generatedBy}`,
    sections,
  ].filter(Boolean).join('\n\n');
}

export function summarizeMemos(memos: EvaluationMemo[]): EvaluationMemoSummary {
  if (memos.length === 0) {
    return { totalEvaluations: 0, approveRate: 0, avgScore: 0, commonIssues: [] };
  }

  const approveCount = memos.filter((memo) => memo.finalVerdict === 'approve').length;
  const issueCounts = new Map<string, number>();
  for (const memo of memos) {
    if (memo.finalVerdict === 'approve') continue;
    for (const section of memo.sections) {
      if (section.priority !== 'high') continue;
      issueCounts.set(section.title, (issueCounts.get(section.title) ?? 0) + 1);
    }
  }

  const commonIssues = [...issueCounts.entries()]
    .filter(([, count]) => count > 1)
    .sort((a, b) => b[1] - a[1])
    .map(([title, count]) => `${title} (${count})`);

  return {
    totalEvaluations: memos.length,
    approveRate: approveCount / memos.length,
    avgScore: memos.reduce((sum, memo) => sum + memo.score, 0) / memos.length,
    commonIssues,
  };
}
