/**
 * Telemetry Seed Data
 * 
 * Initial telemetry from 48-example dogfood audit (2026-03-31).
 * This provides a baseline for model performance tracking.
 * 
 * @see AUDIT_FINDINGS.md for full analysis
 */

import { GenerationTelemetry } from '../core/TelemetryAggregator.js';

export const SEED_TELEMETRY: GenerationTelemetry[] = [
  // ============================================
  // p5.js - 8 examples, all successful
  // ============================================
  {
    id: 'audit-p5-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 46600,
    outputSizeBytes: 3388,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-p5-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 34900,
    outputSizeBytes: 4175,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-p5-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 109300,
    outputSizeBytes: 3075,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-p5-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 28200,
    outputSizeBytes: 2070,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-p5-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 26000,
    outputSizeBytes: 1929,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-p5-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'p5',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create an interactive generative art scene with animated particles',
    generationTimeMs: 56000,
    outputSizeBytes: 5114,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },

  // ============================================
  // GLSL - 8 examples, all successful
  // ============================================
  {
    id: 'audit-glsl-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 29800,
    outputSizeBytes: 2282,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-glsl-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 10200,
    outputSizeBytes: 715,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-glsl-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 118300,
    outputSizeBytes: 2718,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-glsl-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 29700,
    outputSizeBytes: 1999,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-glsl-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 13600,
    outputSizeBytes: 880,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-glsl-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'glsl',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create a GLSL fragment shader with noise and animation',
    generationTimeMs: 54800,
    outputSizeBytes: 1785,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },

  // ============================================
  // Three.js - 6 successful, 2 FAILED
  // ============================================
  {
    id: 'audit-three-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 36600,
    outputSizeBytes: 6753,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-three-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 33700,
    outputSizeBytes: 6959,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-three-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 90000,
    outputSizeBytes: 66,
    validationPassed: false,
    validationErrors: ['Output too small (66b) - minimum is 800b'],
    success: false,
    error: 'Failed generation - empty output',
  },
  {
    id: 'audit-three-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 33900,
    outputSizeBytes: 3635,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-three-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 24600,
    outputSizeBytes: 2361,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-three-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'three',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create a 3D scene with animated objects',
    generationTimeMs: 54200,
    outputSizeBytes: 3822,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },

  // ============================================
  // Hydra - 4 successful, 4 FAILED/TOO SMALL
  // ============================================
  {
    id: 'audit-hydra-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 8700,
    outputSizeBytes: 415,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-hydra-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 13000,
    outputSizeBytes: 139,
    validationPassed: false,
    validationErrors: ['Hydra code is too small (139b) - minimum is 200b'],
    success: false,
    error: 'Output too small - incomplete Hydra code',
  },
  {
    id: 'audit-hydra-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 2800,
    outputSizeBytes: 74,
    validationPassed: false,
    validationErrors: ['Hydra code is too small (74b) - minimum is 200b'],
    success: false,
    error: 'Failed generation - empty output',
  },
  {
    id: 'audit-hydra-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 3600,
    outputSizeBytes: 169,
    validationPassed: false,
    validationErrors: ['Hydra code is too small (169b) - minimum is 200b'],
    success: false,
    error: 'Output too small - incomplete Hydra code',
  },
  {
    id: 'audit-hydra-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 10400,
    outputSizeBytes: 307,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-hydra-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'hydra',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create live visuals with osc and modulate',
    generationTimeMs: 38900,
    outputSizeBytes: 181,
    validationPassed: false,
    validationErrors: ['Hydra code is too small (181b) - minimum is 200b'],
    success: false,
    error: 'Output too small - incomplete Hydra code',
  },

  // ============================================
  // Strudel - 6 successful
  // ============================================
  {
    id: 'audit-strudel-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 25800,
    outputSizeBytes: 245,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-strudel-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 7700,
    outputSizeBytes: 312,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-strudel-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 60000,
    outputSizeBytes: 1337,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-strudel-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 7000,
    outputSizeBytes: 313,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-strudel-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 11200,
    outputSizeBytes: 531,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-strudel-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'strudel',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create a drum pattern with s("bd sd")',
    generationTimeMs: 57500,
    outputSizeBytes: 381,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },

  // ============================================
  // Remotion - 6 successful
  // ============================================
  {
    id: 'audit-remotion-minimax-m2.7',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'minimax-m2.7',
    provider: 'minimax',
    prompt: 'Create a video component with animation',
    generationTimeMs: 31000,
    outputSizeBytes: 2234,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-remotion-minimax-m2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'minimax-m2.5',
    provider: 'minimax',
    prompt: 'Create a video component with animation',
    generationTimeMs: 13100,
    outputSizeBytes: 1698,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-remotion-qwen35-9b',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'qwen3.5-9b',
    provider: 'qwen',
    prompt: 'Create a video component with animation',
    generationTimeMs: 52600,
    outputSizeBytes: 2507,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-remotion-qwen-coder-40b',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'qwen3-coder-40b',
    provider: 'qwen',
    prompt: 'Create a video component with animation',
    generationTimeMs: 20600,
    outputSizeBytes: 2307,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-remotion-gemma3-4b',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'gemma3-4b',
    provider: 'ollama',
    prompt: 'Create a video component with animation',
    generationTimeMs: 24900,
    outputSizeBytes: 1483,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },
  {
    id: 'audit-remotion-kimi-k2.5',
    timestamp: new Date('2026-03-31'),
    domain: 'remotion',
    modelId: 'kimi-k2.5',
    provider: 'kimi',
    prompt: 'Create a video component with animation',
    generationTimeMs: 21200,
    outputSizeBytes: 1654,
    validationPassed: true,
    validationErrors: [],
    success: true,
  },

  // ============================================
  // HTML - Template fallback, all identical
  // ============================================
  ...['minimax-m2.7', 'minimax-m2.5', 'qwen3.5-9b', 'qwen3-coder-40b', 'gemma3-4b', 'kimi-k2.5'].map((modelId, i) => ({
    id: `audit-html-${modelId}`,
    timestamp: new Date('2026-03-31'),
    domain: 'html',
    modelId,
    provider: modelId.includes('minimax') ? 'minimax' : modelId.includes('qwen') ? 'qwen' : modelId.includes('gemma') ? 'ollama' : 'kimi',
    prompt: 'Create HTML page',
    generationTimeMs: 40,
    outputSizeBytes: 645,
    validationPassed: true,
    validationErrors: [],
    success: true,
  })),

  // ============================================
  // ASCII - Template fallback, all identical
  // ============================================
  ...['minimax-m2.7', 'minimax-m2.5', 'qwen3.5-9b', 'qwen3-coder-40b', 'gemma3-4b', 'kimi-k2.5'].map((modelId, i) => ({
    id: `audit-ascii-${modelId}`,
    timestamp: new Date('2026-03-31'),
    domain: 'ascii',
    modelId,
    provider: modelId.includes('minimax') ? 'minimax' : modelId.includes('qwen') ? 'qwen' : modelId.includes('gemma') ? 'ollama' : 'kimi',
    prompt: 'Create ASCII art',
    generationTimeMs: 40,
    outputSizeBytes: 1829,
    validationPassed: true,
    validationErrors: [],
    success: true,
  })),
] as GenerationTelemetry[];

/**
 * Summary statistics from seed data
 */
export const SEED_SUMMARY = {
  totalExamples: 48,
  successfulGenerations: 46,
  failedGenerations: 2,
  tooSmallGenerations: 6,
  overallSuccessRate: 0.96,
  domainSuccessRates: {
    'p5': 1.0,        // 6/6
    'glsl': 1.0,      // 6/6
    'three': 0.83,    // 5/6 (1 failed)
    'hydra': 0.5,     // 2/4 (2 too small)
    'strudel': 1.0,   // 6/6
    'remotion': 1.0,  // 6/6
    'html': 1.0,      // 6/6 (template)
    'ascii': 1.0,     // 6/6 (template)
  },
  modelsToAvoid: {
    'three': ['qwen3.5-9b'],
    'hydra': ['qwen3.5-9b', 'minimax-m2.5', 'qwen3-coder-40b', 'kimi-k2.5'],
  },
  slowModels: ['qwen3.5-9b'],
  fastModels: ['gemma3-4b', 'minimax-m2.5'],
  qualityLeaders: {
    'p5': ['minimax-m2.5', 'minimax-m2.7', 'kimi-k2.5'],
    'glsl': ['minimax-m2.7', 'kimi-k2.5', 'qwen3-coder-40b'],
    'three': ['minimax-m2.7', 'minimax-m2.5'],
    'hydra': ['minimax-m2.7', 'gemma3-4b'],
    'strudel': ['qwen3-coder-40b', 'gemma3-4b'],
    'remotion': ['minimax-m2.7', 'qwen3-coder-40b', 'qwen3.5-9b'],
  },
};
