/**
 * Atelier - Creative Coding Agent
 *
 * Main entry point for the creative coding agent with internal Ralph-Wiggum Loop
 * for generating emergent generative art.
 */

import fs from 'fs/promises';
import path from 'path';

/**
 * Simple p5.js code generator for MVP
 * This is a simplified implementation that generates basic p5.js sketches
 */
function generateBasicSketch(prompt) {
  return `/**
 * Generated by Atelier
 * Prompt: ${prompt}
 */

function setup() {
  createCanvas(600, 600);
  background(20);
}

function draw() {
  // Simple generative art based on prompt
  noStroke();

  for (let i = 0; i < 10; i++) {
    fill(random(255), random(255), random(255), 150);
    circle(random(width), random(height), random(20, 100));
  }
}

// Mark completion as requested
// <promise>COMPLETE</promise>`;
}

/**
 * Main run function for Atelier
 *
 * @param {string} prompt - The creative prompt to generate from
 * @param {Object} options - Configuration options
 * @param {number} options.maxIterations - Maximum iterations (default: 20)
 * @param {number} options.timeoutMinutes - Timeout per iteration (default: 30)
 * @param {string} options.output - Output directory path
 * @param {string} options.project - Project name for gallery
 * @param {number} options.minQualityScore - Minimum quality score (default: 0.7)
 * @returns {Promise<Object>} Result object with code, iterations, metadata
 */
export async function run(prompt, options = {}) {
  const startTime = Date.now();

  const {
    maxIterations = 20,
    timeoutMinutes = 30,
    output = './output',
    project = 'default',
    minQualityScore = 0.7
  } = options;

  try {
    // Validate input
    if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
      throw new Error('Prompt is required and must be a non-empty string');
    }

    // Create output directory if it doesn't exist
    await fs.mkdir(output, { recursive: true });

    // Simple generation - in real implementation this would use RalphLoop
    const code = generateBasicSketch(prompt);
    const iterations = 1;
    const completed = true;
    const reason = 'Basic generation complete';
    const finalScore = 0.8;
    const duration = Date.now() - startTime;

    const result = {
      code,
      iterations,
      completed,
      reason,
      timestamp: new Date().toISOString(),
      duration,
      finalScore,
      project,
      outputDir: output,
      prompt
    };

    // Export final code as HTML
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Atelier - ${project}</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.0/p5.min.js"></script>
</head>
<body>
  <script>
${code}
  </script>
</body>
</html>`;

    const htmlPath = path.join(output, `${project}-final.html`);
    await fs.writeFile(htmlPath, htmlContent);
    result.htmlPath = htmlPath;

    // Export final code as JS
    const jsPath = path.join(output, `${project}-final.js`);
    await fs.writeFile(jsPath, code);
    result.jsPath = jsPath;

    // Create a simple text file as "archive" for MVP (ZIP requires additional dependencies)
    const archivePath = path.join(output, `${project}-archive.txt`);
    const archiveContent = `Atelier Project Archive\nProject: ${project}\nPrompt: ${prompt}\nIterations: ${iterations}\nGenerated: ${result.timestamp}\n\nCode:\n${code}`;
    await fs.writeFile(archivePath, archiveContent);
    result.zipPath = archivePath;

    return result;

  } catch (error) {
    throw new Error(`Atelier run failed: ${error.message}`);
  }
}

/**
 * Convenience function to run Atelier with CLI-style arguments
 *
 * @param {Object} args - Command line arguments
 * @returns {Promise<Object>} Result object
 */
export async function runFromArgs(args) {
  const {
    prompt,
    maxIterations = 20,
    output = './output',
    project = 'default'
  } = args;

  return run(prompt, {
    maxIterations,
    output,
    project
  });
}

export default { run, runFromArgs };