/**
 * RalphLoop tests - Loop start + context (seed, no-placeholder fallback)
 * Uses ContextAccumulation.getHistory() to assert on usedPrompt (no jest mocks).
 */
import { RalphLoop } from '../../dist/core/RalphLoop.js';
import { ContextAccumulation } from '../../dist/core/ContextAccumulation.js';
import path from 'path';
import os from 'os';

const TEST_GALLERY_DIR = path.join(os.tmpdir(), 'atelier-ralph-loop-test');

function getResultCode(result: { code: string }): string {
  return result.code;
}

describe('RalphLoop', () => {
  beforeEach(() => {
    RalphLoop.reset();
    delete process.env.INCEPTION_API_KEY;
    delete process.env.ATELIER_LLM_API_KEY;
  });

  describe('generator routing by prompt keywords', () => {
    afterEach(() => {
      RalphLoop.reset();
    });

    it('prompt "blue particles" uses ParticleSystem generator (code contains ParticleSystem signature)', async () => {
      const result = await RalphLoop.run('blue particles', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'particle-routing-test'
      });
      const code = getResultCode(result);
      expect(code).toContain('Generated by Atelier ParticleSystem');
      expect(code).toContain('class Particle');
    });

    it('prompt "lenia style" uses CellularAutomata generator (code contains CellularAutomata signature)', async () => {
      const result = await RalphLoop.run('lenia style', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'lenia-routing-test'
      });
      const code = getResultCode(result);
      expect(code).toContain('Generated by Atelier CellularAutomata');
      expect(code).toContain('function updateGrid()');
    });
  });

  describe('organism mode (W1-O)', () => {
    it('mode=organism uses generateMusicToVisual per iteration and saves organism to gallery', async () => {
      const result = await RalphLoop.run('ambient glitch', {
        mode: 'organism',
        maxIterations: 2,
        galleryDir: TEST_GALLERY_DIR,
        project: 'organism-mode-test',
        traits: { bpm: 90 },
      });
      expect(result.iterations).toBe(2);
      expect(result.completed).toBe(true);
      expect(result.code).toContain('setcps');
      const { Gallery } = await import('../../dist/gallery/Gallery.js');
      const gallery = new Gallery(TEST_GALLERY_DIR);
      const dateStr = new Date().toISOString().split('T')[0];
      const history = await gallery.loadHistoryFromDir(`${dateStr}--organism-mode-test`);
      expect(history.length).toBe(2);
      expect((history[0] as { type?: string }).type).toBe('organism');
      expect((history[0] as { musicCode?: string }).musicCode).toBeDefined();
      expect((history[0] as { visualCode?: string }).visualCode).toBeDefined();
    });
  });

  describe('seed and context', () => {
    it('run with seedCode produces iteration 1 context that includes the seed text', async () => {
      const seedCode = 'function setup() { createCanvas(400, 400); }';
      await RalphLoop.run('make it colorful', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'seed-test',
        seedCode
      });

      const history = ContextAccumulation.getHistory() as { usedPrompt: string }[];
      expect(history).toHaveLength(1);
      const usedPrompt = history[0].usedPrompt;
      expect(usedPrompt).toContain("Here is the seed/template; improve it toward the user's goal.");
      expect(usedPrompt).toContain('Seed:\n');
      expect(usedPrompt).toContain(seedCode);
    });

    it('run with seedTemplate produces iteration 1 context that includes the template', async () => {
      const seedTemplate = 'template: minimal p5 sketch';
      await RalphLoop.run('add particles', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'template-test',
        seedTemplate
      });

      const history = ContextAccumulation.getHistory() as { usedPrompt: string }[];
      expect(history).toHaveLength(1);
      const usedPrompt = history[0].usedPrompt;
      expect(usedPrompt).toContain("Here is the seed/template; improve it toward the user's goal.");
      expect(usedPrompt).toContain(seedTemplate);
    });
  });

  describe('no {{context}} placeholder fallback', () => {
    it('prompt with NO {{context}} placeholder still results in usedPrompt containing "Context from previous iterations"', async () => {
      const promptWithNoPlaceholder = 'Just draw a circle.';
      await RalphLoop.run(promptWithNoPlaceholder, {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'no-context-placeholder-test'
      });

      const history = ContextAccumulation.getHistory() as { usedPrompt: string }[];
      expect(history).toHaveLength(1);
      const usedPrompt = history[0].usedPrompt;
      expect(usedPrompt).toContain('Context from previous iterations');
      expect(usedPrompt).toContain(promptWithNoPlaceholder);
    });
  });

  describe('onProgress and signal (Run/Stop, timeline)', () => {
    it('calls onProgress after each iteration with iteration, score, promiseDetected, code, timestamp', async () => {
      const progressCalls: { iteration: number; score: number; promiseDetected: boolean; code: string; timestamp: string }[] = [];
      await RalphLoop.run('blue particles', {
        maxIterations: 2,
        galleryDir: TEST_GALLERY_DIR,
        project: 'onprogress-test',
        onProgress: (data) => progressCalls.push(data)
      });
      expect(progressCalls.length).toBeGreaterThanOrEqual(1);
      expect(progressCalls[0]).toMatchObject({
        iteration: 1,
        score: expect.any(Number),
        promiseDetected: expect.any(Boolean),
        code: expect.any(String),
        timestamp: expect.any(String)
      });
      expect(progressCalls[0].code.length).toBeGreaterThan(0);
      expect(progressCalls[0].timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    });

    it('stops when signal is aborted and returns reason "aborted by user"', async () => {
      const ac = new AbortController();
      const progressCalls: number[] = [];
      const runPromise = RalphLoop.run('blue particles', {
        maxIterations: 5,
        galleryDir: TEST_GALLERY_DIR,
        project: 'abort-test',
        signal: ac.signal,
        onProgress: (data) => {
          progressCalls.push(data.iteration);
          if (data.iteration >= 1) ac.abort();
        }
      });
      const result = await runPromise;
      expect(result.reason).toBe('aborted by user');
      expect(progressCalls.length).toBeLessThanOrEqual(2);
    });
  });

  describe('merge-every-N (W1-B)', () => {
    it('with mergeEveryN=2, every 2nd iteration runs a merge step (two from history, proposed)', async () => {
      const mergeSteps: { codeA: string; codeB: string; proposed: string }[] = [];
      await RalphLoop.run('blue particles', {
        maxIterations: 4,
        galleryDir: TEST_GALLERY_DIR,
        project: 'merge-every-n-test',
        mergeEveryN: 2,
        onMergeStep: (data) => mergeSteps.push(data),
      });
      expect(mergeSteps.length).toBe(2);
      expect(mergeSteps[0].codeA).toBeDefined();
      expect(mergeSteps[0].codeB).toBeDefined();
      // Smart merge extracts setup from A and draw from B — verify output is valid p5.js
      expect(mergeSteps[0].proposed).toMatch(/function\s+setup\s*\(/);
      expect(mergeSteps[0].proposed).toMatch(/function\s+draw\s*\(/);
      expect(mergeSteps[1].proposed).toMatch(/function\s+setup\s*\(/);
      expect(mergeSteps[1].proposed).toMatch(/function\s+draw\s*\(/);
    });
  });

  describe('deep collaboration integration', () => {
    it('loop works normally without collab options (existing behavior preserved)', async () => {
      const result = await RalphLoop.run('blue particles', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'no-collab-test'
      });
      expect(result.iterations).toBe(1);
      expect(result.code).toBeDefined();
      expect(result.code.length).toBeGreaterThan(0);
    });

    it('loop accepts useDeepCollab option without errors', async () => {
      // This test verifies the option is accepted and doesn't break the loop
      // Actual collaboration behavior is tested in integration tests
      const result = await RalphLoop.run('blue particles', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'deep-collab-test',
        useDeepCollab: true,
        collabConfig: {
          maxPhases: 2,
        },
      });
      expect(result.iterations).toBe(1);
      expect(result.code).toBeDefined();
    });

    it('loop accepts useCollab option without errors', async () => {
      const result = await RalphLoop.run('blue particles', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'simple-collab-test',
        useCollab: true,
        collabConfig: {
          maxRounds: 2,
        },
      });
      expect(result.iterations).toBe(1);
      expect(result.code).toBeDefined();
    });

    it('loop accepts collabDomain option', async () => {
      const result = await RalphLoop.run('draw a circle', {
        maxIterations: 1,
        galleryDir: TEST_GALLERY_DIR,
        project: 'collab-domain-test',
        useDeepCollab: true,
        collabDomain: 'p5',
      });
      expect(result.iterations).toBe(1);
      expect(result.code).toBeDefined();
    });
  });
});
