import { describe, it, expect, vi, beforeEach } from 'vitest';
import { LiminalCortex } from '../../../src/cortex/LiminalCortex.js';
import type { CortexSnapshot, CortexConfig } from '../../../src/cortex/types.js';
import type { CortexEvent } from '../../../src/cortex/LiminalCortex.js';
const { mockSnapshot, mockGoals, mockOnEvent } = vi.hoisted(() => ({ mockSnapshot: vi.fn(), mockGoals: vi.fn(), mockOnEvent: vi.fn() }));
function mkS(o: Partial<CortexSnapshot> = {}): CortexSnapshot { return { timestamp: new Date().toISOString(), taskPipeline: { pending: 0, inProgress: 0, completed: 10, failed: 0, skipped: 0, acceptanceRate: 0.9, failureBreakdown: {} }, llmHealth: { avgLatencyMs: 500, successRate: 0.95, recentErrorCount: 0, lastError: null, activeProvider: 't', activeModel: 't' }, scoreTrend: { scores: [0.7, 0.75, 0.8], average: 0.75, count: 3 }, activeProcesses: [], eventsProcessed: 50, ...o }; }
function mkC(o: Partial<CortexConfig> = {}): CortexConfig { return { loopIntervalMs: 100, maxConsecutiveFailures: 3, budgetActionsLimit: 10, budgetTokenLimit: 50000, autonomyLevel: 'assist', ...o }; }
describe('LiminalCortex', () => {
  let pb: { getSnapshot: ReturnType<typeof vi.fn> }; let gs: { getActiveGoals: ReturnType<typeof vi.fn> };
  beforeEach(() => { vi.clearAllMocks(); pb = { getSnapshot: mockSnapshot }; gs = { getActiveGoals: mockGoals }; mockSnapshot.mockReturnValue(mkS()); mockGoals.mockReturnValue([]); });
  function mk(c?: Partial<CortexConfig>) { return new LiminalCortex({ perceptionBus: pb as any, goalStore: gs as any, config: mkC(c), onEvent: mockOnEvent }); }
  it('starts', () => { const c = mk({ loopIntervalMs: 60000 }); c.start(); expect(c.isRunning()).toBe(true); c.stop(); });
  it('stops', () => { const c = mk({ loopIntervalMs: 60000 }); c.start(); c.stop(); expect(c.isRunning()).toBe(false); });
  it('no double-start', () => { const c = mk({ loopIntervalMs: 60000 }); c.start(); c.start(); expect(c.isRunning()).toBe(true); c.stop(); });
  it('tick returns snapshot and proposals', () => { const r = mk().tick(); const { timestamp: _t, ...rest } = r.snapshot; expect(rest).toEqual((() => { const { timestamp, ...rest } = mkS(); return rest; })()); expect(r.proposals).toBeInstanceOf(Array); });
  it('tick reads goals', () => { mockGoals.mockReturnValue([{ id: 'g1', text: 'G', priority: 'normal', category: 'maintenance', status: 'active', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }]); expect(mk().tick().goals).toHaveLength(1); });
  it('tick produces proposals from weakness', () => { mockSnapshot.mockReturnValue(mkS({ taskPipeline: { pending: 0, inProgress: 0, completed: 3, failed: 5, skipped: 0, acceptanceRate: 0.3, failureBreakdown: { timeout: 5 } } })); expect(mk().tick().proposals.length).toBeGreaterThanOrEqual(1); });
  it('budget starts at zero', () => { const u = mk().getBudgetUsage(); expect(u.actionsTaken).toBe(0); expect(u.actionsLimit).toBe(10); });
  it('emits loop_tick', async () => { vi.useFakeTimers(); const c = mk({ loopIntervalMs: 50 }); c.start(); await vi.advanceTimersByTimeAsync(180); c.stop(); expect(mockOnEvent.mock.calls.filter((x: any[]) => x[0].type === 'cortex.loop_tick').length).toBeGreaterThanOrEqual(2); vi.useRealTimers(); });
  it('emits action_proposed', async () => { mockSnapshot.mockReturnValue(mkS({ taskPipeline: { pending: 0, inProgress: 0, completed: 3, failed: 5, skipped: 0, acceptanceRate: 0.3, failureBreakdown: {} } })); vi.useFakeTimers(); const c = mk({ loopIntervalMs: 50 }); c.start(); await vi.advanceTimersByTimeAsync(120); c.stop(); expect(mockOnEvent.mock.calls.filter((x: any[]) => x[0].type === 'cortex.action_proposed').length).toBeGreaterThanOrEqual(1); vi.useRealTimers(); });
  it('circuit breaker trips', async () => { mockSnapshot.mockImplementation(() => { throw new Error('fail'); }); vi.useFakeTimers(); const c = mk({ loopIntervalMs: 50, maxConsecutiveFailures: 2 }); c.start(); await vi.advanceTimersByTimeAsync(500); expect(c.isRunning()).toBe(false); expect(mockOnEvent.mock.calls.find((x: any[]) => x[0].data?.circuitBreakerTripped === true)).not.toBeUndefined(); vi.useRealTimers(); });
  it('events have tickNumber and timestamp', async () => { vi.useFakeTimers(); const c = mk({ loopIntervalMs: 50 }); c.start(); await vi.advanceTimersByTimeAsync(80); c.stop(); for (const call of mockOnEvent.mock.calls) { const e = call[0] as CortexEvent; expect(e.tickNumber).toBeGreaterThanOrEqual(1); expect(e.timestamp).toBeTruthy(); } vi.useRealTimers(); });
  it('tick returns supervision result', () => { const r = mk().tick(); expect(r.supervision).not.toBeNull(); expect(r.supervision.stuckWorkers).toBeInstanceOf(Array); expect(r.supervision.expiredLeases).toBeInstanceOf(Array); });
  it('detects stuck workers via snapshot processes', () => { const past = new Date(Date.now() - 3 * 60 * 1000).toISOString(); mockSnapshot.mockReturnValue(mkS({ activeProcesses: [{ name: 'Generate particles', startedAt: past }] })); const r = mk().tick(); expect(r.supervision.stuckWorkers.length).toBeGreaterThanOrEqual(1); expect(r.supervision.stuckWorkers[0].processName).toBe('Generate particles'); });
  it('emits stuck_detected when workers are stuck', async () => { const past = new Date(Date.now() - 3 * 60 * 1000).toISOString(); mockSnapshot.mockReturnValue(mkS({ activeProcesses: [{ name: 'Generate particles', startedAt: past }] })); vi.useFakeTimers(); const c = mk({ loopIntervalMs: 50 }); c.start(); await vi.advanceTimersByTimeAsync(120); c.stop(); const stuckEvents = mockOnEvent.mock.calls.filter((x: any[]) => x[0].type === 'cortex.stuck_detected'); expect(stuckEvents.length).toBeGreaterThanOrEqual(1); expect(stuckEvents[0][0].data.stuckWorkers).not.toBeNull(); vi.useRealTimers(); });
});
