import { hashCode } from '../../utils/hashCode.js';

/**
 * CellularAutomata - Specialized generator for p5.js cellular automata
 *
 * Generates advanced cellular automata code with:
 * - Lenia-style continuous CA with smooth rules
 * - Organic-looking patterns
 * - Multiple neighborhood types
 * - Convolution operations with custom kernels
 * - Multi-species support
 *
 * Usage: CellularAutomata.generate({ type: 'lenia', resolution: 5, radius: 15 })
 */
export class CellularAutomata {
  /**
   * Generate p5.js cellular automata code
   *
   * @param params - Configuration object for cellular automata
   * @returns Valid p5.js cellular automata code string
   */
  static generate(params: unknown = {}): string {
    const config = this.normalizeParams(params);
    return this.generateCellularAutomataCode(config);
  }

  /**
   * Normalize and validate parameters
   *
   * @param params - Raw parameters (any type)
   * @returns Normalized configuration object
   */
  private static normalizeParams(params: unknown): CAConfig {
    if (params === null || params === undefined) {
      return this.getDefaultConfig();
    }

    if (typeof params === 'object') {
      const obj = params as Record<string, unknown>;
      return {
        type: this.getString(obj.type, 'lenia'),
        resolution: this.getNumber(obj.resolution, 5),
        radius: this.getNumber(obj.radius, 15),
        timeStep: this.getNumber(obj.timeStep, 0.1),
        width: this.getNumber(obj.width, 600),
        height: this.getNumber(obj.height, 600),
        colorMapping: this.getString(obj.colorMapping, 'state'),
        palette: this.getString(obj.palette, 'bioluminescent'),
        colorMode: this.getString(obj.colorMode, 'RGB'),
        neighborhood: this.getString(obj.neighborhood, 'circular'),
        boundary: this.getString(obj.boundary, 'wrap'),
        kernel: this.getString(obj.kernel, 'ring'),
        species: this.getNumber(obj.species, 1),
        activation: this.getString(obj.activation, 'sigmoid'),
        organic: Boolean(obj.organic),
        continuous: Boolean(obj.continuous),
        smoothing: Boolean(obj.smoothing),
        interpolation: this.getString(obj.interpolation, 'bilinear'),
        renderMode: this.getString(obj.renderMode, 'cells'),
        mouseInteraction: Boolean(obj.mouseInteraction),
        symmetry: this.getNumber(obj.symmetry, 0),
        initialPattern: this.getString(obj.initialPattern, 'random'),
        mutationRate: this.getNumber(obj.mutationRate, 0),
        mutationStrength: this.getNumber(obj.mutationStrength, 0),
        scales: this.getNumber(obj.scales, 1),
        customPattern: this.getString(obj.customPattern, ''),
        description: this.getString(obj.description, ''),
        rules: obj.rules as Record<string, unknown> | undefined
      };
    }

    return this.getDefaultConfig();
  }

  /**
   * Get number value with default
   */
  private static getNumber(value: unknown, defaultValue: number): number {
    if (typeof value === 'number' && !isNaN(value) && isFinite(value)) {
      return Math.max(0, value);
    }
    return defaultValue;
  }

  /**
   * Get string value with default
   */
  private static getString(value: unknown, defaultValue: string): string {
    return typeof value === 'string' ? value : defaultValue;
  }

  /**
   * Get default configuration
   */
  private static getDefaultConfig(): CAConfig {
    return {
      type: 'lenia',
      resolution: 5,
      radius: 15,
      timeStep: 0.1,
      width: 600,
      height: 600,
      colorMapping: 'state',
      palette: 'bioluminescent',
      colorMode: 'RGB',
      neighborhood: 'circular',
      boundary: 'wrap',
      kernel: 'ring',
      species: 1,
      activation: 'sigmoid',
      organic: true,
      continuous: true,
      smoothing: true,
      interpolation: 'bilinear',
      renderMode: 'cells',
      mouseInteraction: false,
      symmetry: 0,
      initialPattern: 'random',
      mutationRate: 0,
      mutationStrength: 0,
      scales: 1,
      customPattern: '',
      description: '',
      rules: undefined
    };
  }

  /**
   * Generate cellular automata code
   */
  private static generateCellularAutomataCode(config: CAConfig): string {
    const seed = this.generateSeed(config);

    let code = `// Generated by Atelier CellularAutomata
// Type: ${config.type}
${config.type === 'lenia' ? '// Lenia-style continuous CA with organic blob patterns\n' : ''}
${config.description !== '' ? `// Description: ${config.description.substring(0, 100)}\n` : ''}
// Seed: ${seed}

`;

    // Add grid setup
    code += this.generateGridSetup(config);

    // Add setup function
    code += this.generateSetupFunction(config);

    // Add draw function
    code += this.generateDrawFunction(config);

    // Add helper functions
    code += this.generateHelperFunctions(config);

    return code;
  }

  /**
   * Generate grid setup
   */
  private static generateGridSetup(config: CAConfig): string {
    const resolution = Math.max(1, Math.floor(config.resolution));
    return `let grid;
let nextGrid;
let resolution = ${resolution};
let cols, rows;
let radius = ${config.radius};
let timeStep = ${config.timeStep};

`;
  }

  /**
   * Generate setup function
   */
  private static generateSetupFunction(config: CAConfig): string {
    let setup = `function setup() {
  createCanvas(${config.width}, ${config.height});
  colorMode(${config.colorMode});
  cols = floor(width / resolution);
  rows = floor(height / resolution);

  grid = createGrid(cols, rows);
  nextGrid = createGrid(cols, rows);

`;

    // Add initialization based on pattern
    setup += this.generateInitialization(config);

    setup += `}
`;

    return setup;
  }

  /**
   * Generate initialization code
   */
  private static generateInitialization(config: CAConfig): string {
    let init = '  ';

    switch (config.initialPattern) {
      case 'random':
        init += `// Random initialization
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      grid[i][j] = random(1);
    }
  }`;
        break;

      case 'center':
        init += `// Center organic blob pattern - circle/orb formation
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let dx = i - cols / 2;
      let dy = j - rows / 2;
      let dist = sqrt(dx * dx + dy * dy);
      grid[i][j] = exp(-dist * dist / 100);  // Organic circular blob
    }
  }`;
        break;

      case 'symmetric':
        const sym = config.symmetry > 0 ? config.symmetry : 6;
        init += `// Symmetric initialization (${sym}-fold)
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let dx = i - cols / 2;
      let dy = j - rows / 2;
      let angle = atan2(dy, dx);
      let dist = sqrt(dx * dx + dy * dy);
      let symmetry = cos(angle * ${sym});
      grid[i][j] = exp(-dist * dist / 200) * (symmetry > 0 ? 1 : 0.5);
    }
  }`;
        break;

      case 'custom':
        init += `// Custom pattern initialization
  ${config.customPattern !== '' ? config.customPattern : '// Random fallback'}
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      if (grid[i][j] === undefined) {
        grid[i][j] = random(1);
      }
    }
  }`;
        break;

      default:
        init += `// Default random initialization
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      grid[i][j] = random(1);
    }
  }`;
    }

    return init;
  }

  /**
   * Generate draw function
   */
  private static generateDrawFunction(config: CAConfig): string {
    let draw = `function draw() {
  background(${this.getBackgroundColor(config)});

`;

    // Add mouse interaction if enabled
    if (config.mouseInteraction) {
      draw += this.generateMouseInteraction(config);
    }

    // Add CA update step
    draw += `  // Update CA state
  updateGrid();

  // Render CA
  ${this.generateRenderCall(config)}
`;

    // Add mutation if enabled
    if (config.mutationRate > 0) {
      draw += this.generateMutation(config);
    }

    draw += `}
`;

    return draw;
  }

  /**
   * Generate mouse interaction code
   */
  private static generateMouseInteraction(config: CAConfig): string {
    return `  // Mouse interaction
  if (mouseIsPressed) {
    let mx = floor(mouseX / resolution);
    let my = floor(mouseY / resolution);
    let influenceRadius = ${Math.floor(config.radius / 2)};

    for (let i = -influenceRadius; i <= influenceRadius; i++) {
      for (let j = -influenceRadius; j <= influenceRadius; j++) {
        let x = (mx + i + cols) % cols;
        let y = (my + j + rows) % rows;
        let dist = sqrt(i * i + j * j);
        if (dist < influenceRadius) {
          grid[x][y] = lerp(grid[x][y], 1, 0.1);
        }
      }
    }
  }

`;
  }

  /**
   * Generate render call
   */
  private static generateRenderCall(config: CAConfig): string {
    switch (config.renderMode) {
      case 'heatmap':
        return `renderHeatmap();`;
      case 'contours':
        return `renderContours();`;
      case 'cells':
      default:
        return `renderCells();`;
    }
  }

  /**
   * Generate helper functions
   */
  private static generateHelperFunctions(config: CAConfig): string {
    let helpers = '';

    // Grid creation
    helpers += `function createGrid(cols, rows) {
  let arr = new Array(cols);
  for (let i = 0; i < arr.length; i++) {
    arr[i] = new Array(rows);
    for (let j = 0; j < rows; j++) {
      arr[i][j] = 0;
    }
  }
  return arr;
}

`;

    // Main update function based on type
    if (config.type === 'lenia') {
      helpers += this.generateLeniaUpdate(config);
    } else if (config.type === 'game-of-life') {
      helpers += this.generateGameOfLifeUpdate(config);
    } else {
      helpers += this.generateCustomUpdate(config);
    }

    // Rendering functions
    helpers += this.generateRenderFunctions(config);

    // Kernel function for Lenia
    if (config.type === 'lenia') {
      helpers += this.generateKernelFunction(config);
    }

    return helpers;
  }

  /**
   * Generate Lenia-style continuous update
   */
  private static generateLeniaUpdate(config: CAConfig): string {
    const smoothing = config.smoothing;

    return `function updateGrid() {
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let state = grid[i][j];
      let neighborhood = computeNeighborhood(i, j);
      let newState = applyGrowthFunction(state, neighborhood);

      ${smoothing ? `// Smooth transition using interpolation
      nextGrid[i][j] = lerp(state, newState, timeStep);` : `
      // Direct update
      nextGrid[i][j] = newState;`}
    }
  }

  // Swap grids
  let temp = grid;
  grid = nextGrid;
  nextGrid = temp;
}

function computeNeighborhood(x, y) {
  let sum = 0;
  let weightSum = 0;

  for (let i = -radius; i <= radius; i++) {
    for (let j = -radius; j <= radius; j++) {
      let nx = (x + i + cols) % cols;  // Wrap boundaries
      let ny = (y + j + rows) % rows;  // Toroidal edge handling

      let dist = sqrt(i * i + j * j);
      if (dist <= radius && dist > 0) {
        let weight = kernelWeight(dist);
        sum += grid[nx][ny] * weight;
        weightSum += weight;
      }
    }
  }

  return sum / weightSum;
}

function applyGrowthFunction(state, neighborhood) {
  let activation;

  ${this.generateActivationFunction(config)}

  return constrain(activation, 0, 1);
}

`;
  }

  /**
   * Generate activation function
   */
  private static generateActivationFunction(config: CAConfig): string {
    switch (config.activation) {
      case 'sigmoid':
        return `  // Sigmoid activation
  let center = 0.5;
  let width = 0.1;
  activation = 1 / (1 + exp(-(neighborhood - center) / width));
  activation = state + (activation - state) * 0.1;`;

      case 'tanh':
        return `  // Tanh activation
  activation = tanh((neighborhood - 0.5) * 4);
  activation = (activation + 1) / 2;
  activation = state + (activation - state) * 0.1;`;

      case 'relu':
        return `  // ReLU-like activation
  activation = neighborhood > 0.5 ? neighborhood : 0;
  activation = constrain(activation, 0, 1);
  activation = state + (activation - state) * 0.1;`;

      case 'polynomial':
        return `  // Polynomial growth function
  let x = neighborhood;
  activation = 4 * x * (1 - x);  // Simple quadratic
  activation = state + (activation - state) * 0.1;`;

      default:
        return `  // Default sigmoid activation
  let center = 0.5;
  let width = 0.1;
  activation = 1 / (1 + exp(-(neighborhood - center) / width));
  activation = state + (activation - state) * 0.1;`;
    }
  }

  /**
   * Generate Game of Life update
   */
  private static generateGameOfLifeUpdate(_config: CAConfig): string {
    return `function updateGrid() {
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let state = grid[i][j] > 0.5 ? 1 : 0;
      let neighbors = countNeighbors(i, j);

      if (state === 0 && neighbors === 3) {
        nextGrid[i][j] = 1;
      } else if (state === 1 && (neighbors < 2 || neighbors > 3)) {
        nextGrid[i][j] = 0;
      } else {
        nextGrid[i][j] = state;
      }
    }
  }

  let temp = grid;
  grid = nextGrid;
  nextGrid = temp;
}

function countNeighbors(x, y) {
  let sum = 0;
  for (let i = -1; i <= 1; i++) {
    for (let j = -1; j <= 1; j++) {
      let nx = (x + i + cols) % cols;
      let ny = (y + j + rows) % rows;
      sum += grid[nx][ny] > 0.5 ? 1 : 0;
    }
  }
  return sum - (grid[x][y] > 0.5 ? 1 : 0);
}

`;
  }

  /**
   * Generate custom update
   */
  private static generateCustomUpdate(config: CAConfig): string {
    return `function updateGrid() {
  // Custom CA rules
  ${config.rules ? '// Custom rules enabled' : `
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let neighborhood = computeNeighborhood(i, j);
      nextGrid[i][j] = applyGrowthFunction(grid[i][j], neighborhood);
    }
  }

  let temp = grid;
  grid = nextGrid;
  nextGrid = temp;
`}
}

function computeNeighborhood(x, y) {
  let sum = 0;
  let count = 0;

  for (let i = -radius; i <= radius; i++) {
    for (let j = -radius; j <= radius; j++) {
      let nx = (x + i + cols) % cols;
      let ny = (y + j + rows) % rows;
      let dist = sqrt(i * i + j * j);
      if (dist <= radius) {
        sum += grid[nx][ny];
        count++;
      }
    }
  }

  return sum / count;
}

function applyGrowthFunction(state, neighborhood) {
  // Custom growth function
  let result = state + (neighborhood - 0.5) * 0.1;
  return constrain(result, 0, 1);
}

`;
  }

  /**
   * Generate rendering functions
   */
  private static generateRenderFunctions(config: CAConfig): string {
    let render = '';

    // Cell-based rendering
    render += `function renderCells() {
  noStroke();

  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let x = i * resolution;
      let y = j * resolution;
      let state = grid[i][j];

      fill(${this.getColorExpression(config)});
      rect(x, y, resolution, resolution);
    }
  }
}

`;

    // Heatmap rendering
    render += `function renderHeatmap() {
  loadPixels();

  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let state = grid[i][j];

      for (let px = 0; px < resolution; px++) {
        for (let py = 0; py < resolution; py++) {
          let x = i * resolution + px;
          let y = j * resolution + py;

          if (x < width && y < height) {
            let idx = (y * width + x) * 4;
            let col = ${this.getHeatmapColor(config)};
            pixels[idx] = col.levels[0];
            pixels[idx + 1] = col.levels[1];
            pixels[idx + 2] = col.levels[2];
            pixels[idx + 3] = 255;
          }
        }
      }
    }
  }

  updatePixels();
}

`;

    // Contour rendering
    render += `function renderContours() {
  background(${this.getBackgroundColor(config)});

  strokeWeight(1);
  noFill();

  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let state = grid[i][j];

      if (state > 0.3 && state < 0.7) {
        let x = i * resolution;
        let y = j * resolution;

        stroke(${this.getColorExpression(config)});
        rect(x, y, resolution, resolution);
      }
    }
  }
}

`;

    return render;
  }

  /**
   * Generate kernel function
   */
  private static generateKernelFunction(config: CAConfig): string {
    return `function kernelWeight(dist) {
  let r = radius;

  ${this.generateKernelCode(config)}
}

`;
  }

  /**
   * Generate kernel code based on type
   */
  private static generateKernelCode(config: CAConfig): string {
    switch (config.kernel) {
      case 'ring':
        return `  // Ring kernel (Lenia-style)
  let ringRadius = r * 0.5;
  let ringWidth = r * 0.2;
  let distFromRing = abs(dist - ringRadius);

  if (distFromRing < ringWidth) {
    return exp(-pow(distFromRing / ringWidth, 2));
  }
  return 0;`;

      case 'gaussian':
        return `  // Gaussian kernel
  let sigma = r * 0.3;
  return exp(-pow(dist / sigma, 2));`;

      case 'exponential':
        return `  // Exponential decay kernel
  let decay = 3.0 / r;
  return exp(-dist * decay);`;

      case 'uniform':
        return `  // Uniform kernel
  if (dist <= r) {
    return 1;
  }
  return 0;`;

      case 'mexican-hat':
        return `  // Mexican hat kernel
  let sigma = r * 0.3;
  let r2 = dist * dist;
  let s2 = sigma * sigma;
  return (1 - r2 / s2) * exp(-r2 / (2 * s2));`;

      default:
        return `  // Default ring kernel
  let ringRadius = r * 0.5;
  let ringWidth = r * 0.2;
  let distFromRing = abs(dist - ringRadius);

  if (distFromRing < ringWidth) {
    return exp(-pow(distFromRing / ringWidth, 2));
  }
  return 0;`;
    }
  }

  /**
   * Get background color
   */
  private static getBackgroundColor(config: CAConfig): string {
    switch (config.palette) {
      case 'bioluminescent': return '0';
      case 'thermal': return '20';
      case 'grayscale': return '128';
      case 'rainbow': return '0';
      default: return '0';
    }
  }

  /**
   * Get color expression for cells
   */
  private static getColorExpression(config: CAConfig): string {
    switch (config.colorMapping) {
      case 'state':
        return this.getPaletteColor(config);
      case 'gradient':
        return `lerpColor(color(0, 100, 200), color(255, 100, 50), state)`;
      case 'velocity':
        return `color(state * 255, 100, 255 - state * 255)`;
      default:
        return this.getPaletteColor(config);
    }
  }

  /**
   * Get palette-based color
   */
  private static getPaletteColor(config: CAConfig): string {
    switch (config.palette) {
      case 'bioluminescent':
        return `color(state * 50, state * 255, state * 200)`;
      case 'thermal':
        return `color(state * 255, state * 100, state * 50)`;
      case 'grayscale':
        return `color(state * 255)`;
      case 'rainbow':
        return `color((state * 360) % 360, 80, 90)`;
      default:
        return `color(state * 255)`;
    }
  }

  /**
   * Get heatmap color expression
   */
  private static getHeatmapColor(config: CAConfig): string {
    switch (config.palette) {
      case 'bioluminescent':
        return `color(state * 50, state * 255, state * 200)`;
      case 'thermal':
        return `color(state * 255, state * 100, 50)`;
      case 'grayscale':
        return `color(state * 255)`;
      case 'rainbow':
        return `color((state * 360) % 360, 80, 90)`;
      default:
        return `color(state * 255)`;
    }
  }

  /**
   * Generate mutation code
   */
  private static generateMutation(config: CAConfig): string {
    return `  // Apply random mutation
  if (random() < ${config.mutationRate}) {
    let mx = floor(random(cols));
    let my = floor(random(rows));
    grid[mx][my] += random(-${config.mutationStrength}, ${config.mutationStrength});
    grid[mx][my] = constrain(grid[mx][my], 0, 1);
  }

`;
  }

  /**
   * Generate seed for variation
   */
  private static generateSeed(config: CAConfig): number {
    const combined =
      config.width +
      config.height +
      config.resolution +
      config.radius +
      Date.now() +
      Math.random() * 1000000;
    return Math.abs(hashCode(combined.toString()));
  }
}

/**
 * Configuration interface for cellular automata
 */
interface CAConfig {
  type: string;
  resolution: number;
  radius: number;
  timeStep: number;
  width: number;
  height: number;
  colorMapping: string;
  palette: string;
  colorMode: string;
  neighborhood: string;
  boundary: string;
  kernel: string;
  species: number;
  activation: string;
  organic: boolean;
  continuous: boolean;
  smoothing: boolean;
  interpolation: string;
  renderMode: string;
  mouseInteraction: boolean;
  symmetry: number;
  initialPattern: string;
  mutationRate: number;
  mutationStrength: number;
  scales: number;
  customPattern: string;
  description: string;
  rules?: Record<string, unknown>;
}