/**
 * FlowField - Template-based flow field generator for p5.js
 *
 * Generates p5.js sketches that use Perlin noise-based vector fields
 * to drive particle motion. A generative art staple.
 *
 * Usage: FlowField.generate({ particleCount: 500, scale: 0.005, trailAlpha: 10 })
 */

export interface FlowFieldConfig {
  particleCount: number;
  scale: number;
  speed: number;
  trailAlpha: number;
  palette: string;
  width: number;
  height: number;
  noiseZOffset: number;
  description: string;
}

export class FlowField {
  static generate(params: unknown = {}): string {
    const config = this.normalizeParams(params);
    return this.generateFlowFieldCode(config);
  }

  private static normalizeParams(params: unknown): FlowFieldConfig {
    if (params === null || params === undefined) {
      return this.getDefaultConfig();
    }
    if (typeof params === 'object') {
      const obj = params as Record<string, unknown>;
      return {
        particleCount: this.getNumber(obj.particleCount, 500),
        scale: this.getNumber(obj.scale, 0.005),
        speed: this.getNumber(obj.speed, 2),
        trailAlpha: this.getNumber(obj.trailAlpha, 10),
        palette: this.getString(obj.palette, 'cool'),
        width: this.getNumber(obj.width, 800),
        height: this.getNumber(obj.height, 600),
        noiseZOffset: this.getNumber(obj.noiseZOffset, 0),
        description: this.getString(obj.description, ''),
      };
    }
    return this.getDefaultConfig();
  }

  private static getNumber(value: unknown, defaultValue: number): number {
    if (typeof value === 'number' && !isNaN(value) && isFinite(value)) {
      return Math.max(0, value);
    }
    return defaultValue;
  }

  private static getString(value: unknown, defaultValue: string): string {
    return typeof value === 'string' ? value : defaultValue;
  }

  private static getDefaultConfig(): FlowFieldConfig {
    return {
      particleCount: 500,
      scale: 0.005,
      speed: 2,
      trailAlpha: 10,
      palette: 'cool',
      width: 800,
      height: 600,
      noiseZOffset: 0,
      description: '',
    };
  }

  private static generateFlowFieldCode(config: FlowFieldConfig): string {
    const count = Math.floor(config.particleCount);
    const colorExpr = this.getParticleColor(config.palette);

    return `// Generated by Liminal FlowField
// Particles: ${count}, Scale: ${config.scale}, Speed: ${config.speed}
${config.description !== '' ? `// Description: ${config.description.substring(0, 100)}\n` : ''}

let particles = [];
let cols, rows;
let scl = 20;
let zoff = ${config.noiseZOffset};

function setup() {
  createCanvas(${config.width}, ${config.height});
  cols = floor(width / scl);
  rows = floor(height / scl);

  for (let i = 0; i < ${count}; i++) {
    particles.push(new FlowParticle());
  }
}

function draw() {
  background(0, 0, 0, ${config.trailAlpha});

  for (let particle of particles) {
    let x = particle.pos.x;
    let y = particle.pos.y;

    let col = floor(x / scl);
    let row = floor(y / scl);

    col = constrain(col, 0, cols - 1);
    row = constrain(row, 0, rows - 1);

    let angle = noise(col * ${config.scale}, row * ${config.scale}, zoff) * TWO_PI * 4;
    let v = p5.Vector.fromAngle(angle);
    v.setMag(${config.speed});

    particle.applyForce(v);
    particle.update();
    particle.edges();
    particle.show(${colorExpr});
  }

  zoff += 0.001;
}

class FlowParticle {
  constructor() {
    this.pos = createVector(random(width), random(height));
    this.vel = p5.Vector.random2D();
    this.acc = createVector(0, 0);
    this.maxSpeed = ${config.speed + 1};
    this.prevPos = this.pos.copy();
  }

  applyForce(force) {
    this.acc.add(force);
  }

  update() {
    this.vel.add(this.acc);
    this.vel.limit(this.maxSpeed);
    this.prevPos = this.pos.copy();
    this.pos.add(this.vel);
    this.acc.mult(0);
  }

  edges() {
    if (this.pos.x > width) { this.pos.x = 0; this.prevPos.x = 0; }
    if (this.pos.x < 0) { this.pos.x = width; this.prevPos.x = width; }
    if (this.pos.y > height) { this.pos.y = 0; this.prevPos.y = 0; }
    if (this.pos.y < 0) { this.pos.y = height; this.prevPos.y = height; }
  }

  show(col) {
    stroke(col);
    strokeWeight(1);
    line(this.pos.x, this.pos.y, this.prevPos.x, this.prevPos.y);
  }
}`;
  }

  private static getParticleColor(palette: string): string {
    switch (palette) {
      case 'warm':
        return 'color(255, random(100, 200), random(50, 100), 200)';
      case 'cool':
        return 'color(random(50, 150), random(100, 200), 255, 200)';
      case 'monochrome':
        return 'color(255, 200)';
      case 'rainbow':
        return 'color((frameCount + random(360)) % 360, 80, 100)';
      default:
        return 'color(255, 200)';
    }
  }
}
