/**
 * P5Generator - Base class for generating p5.js sketch code
 *
 * Generates valid p5.js sketch code strings based on prompts and context.
 * This is the base implementation that creates template-based sketches.
 *
 * Key behavior:
 * - generate(prompt, context) returns valid p5.js code string
 * - Handles edge cases (null, undefined, invalid inputs)
 * - Generates variation based on prompt content
 * - Uses context to influence generation
 * - When generating particles or cellular automata, uses ParticleSystem/CellularAutomata
 *   with params derived from the prompt via promptToGeneratorParams().
 */
import { promptToGeneratorParams } from '../../utils/promptToGeneratorParams.js';
import { hashCode } from '../../utils/hashCode.js';
import { ParticleSystem } from './ParticleSystem.js';
import { CellularAutomata } from './CellularAutomata.js';
import { particleConfidence, cellularConfidence } from '../registerGenerators.js';

export class P5Generator {
  /**
   * Generate p5.js sketch code
   *
   * @param prompt - The generation prompt (can be any type, will be stringified)
   * @param context - Optional context object with previous iterations, code, etc.
   * @returns Valid p5.js sketch code string
   */
  static generate(prompt: unknown, context: unknown = {}): string {
    // Normalize inputs to strings
    const promptStr = this.normalizeInput(prompt);
    const contextStr = this.normalizeInput(context);

    // Generate sketch based on prompt analysis
    return this.generateSketch(promptStr, contextStr);
  }

  /**
   * Normalize input to string
   *
   * Handles null, undefined, objects, and other types safely.
   *
   * @param input - Any input type
   * @returns String representation of input
   */
  private static normalizeInput(input: unknown): string {
    if (input === null) return '';
    if (input === undefined) return '';
    if (typeof input === 'string') return input;
    if (typeof input === 'number') return input.toString();
    if (typeof input === 'boolean') return input.toString();
    if (typeof input === 'object') return JSON.stringify(input);
    return String(input);
  }

  /**
   * Generate p5.js sketch based on prompt and context
   *
   * Analyzes the prompt and generates appropriate sketch code.
   * Supports various sketch types: particles, animation, interaction, etc.
   *
   * @param prompt - Normalized prompt string
   * @param context - Normalized context string
   * @returns Valid p5.js code string
   */
  private static generateSketch(prompt: string, context: string): string {
    // Use shared confidence-based routing for specialized generators
    if (particleConfidence(prompt) > 0) {
      return this.generateParticleSystem(prompt, context);
    }
    if (cellularConfidence(prompt) > 0) {
      return this.generateCellularAutomata(prompt, context);
    }

    // Template-based fallbacks for P5Generator
    const promptLower = prompt.toLowerCase();
    if (promptLower.includes('animat') || promptLower.includes('moving')) {
      return this.generateAnimatedSketch(prompt, context);
    } else if (promptLower.includes('mouse') || promptLower.includes('interact')) {
      return this.generateInteractiveSketch(prompt, context);
    } else {
      return this.generateBasicSketch(prompt, context);
    }
  }

  /**
   * Generate basic p5.js sketch
   *
   * @param prompt - The user prompt
   * @param context - Context for generation
   * @returns Basic sketch code
   */
  private static generateBasicSketch(prompt: string, context: string): string {
    const canvasSize = this.extractCanvasSize(prompt);
    const colors = this.extractColors(prompt);
    const seed = this.generateSeed(prompt, context);

    return `// Generated by Atelier P5Generator
// Prompt: ${prompt.substring(0, 100)}
// Seed: ${seed}

function setup() {
  createCanvas(${canvasSize.width}, ${canvasSize.height});
  ${colors.background}
}

function draw() {
  ${colors.fill}

  // Draw dynamic shapes based on time
  const time = millis() * 0.001;
  translate(width / 2, height / 2);

  for (let i = 0; i < 5; i++) {
    push();
    rotate(time * 0.5 + i * TWO_PI / 5);
    translate(50, 0);
    ellipse(0, 0, ${30 + seed % 20}, ${30 + seed % 20});
    pop();
  }
}`;
  }

  /**
   * Generate particle system sketch
   *
   * Uses ParticleSystem.generate() with params derived from prompt (palette, speed, etc.).
   *
   * @param prompt - The user prompt
   * @param context - Context for generation
   * @returns Particle system code
   */
  private static generateParticleSystem(prompt: string, _context: string): string {
    const canvasSize = this.extractCanvasSize(prompt);
    const particleCount = this.extractNumber(prompt) || 100;
    const derived = promptToGeneratorParams(prompt);
    const params = {
      width: canvasSize.width,
      height: canvasSize.height,
      particleCount,
      ...derived
    };
    return ParticleSystem.generate(params);
  }

  /**
   * Generate cellular automata sketch
   *
   * Uses CellularAutomata.generate() with params derived from prompt (palette, timeStep, etc.).
   *
   * @param prompt - The user prompt
   * @param context - Context for generation
   * @returns Cellular automata code
   */
  private static generateCellularAutomata(prompt: string, _context: string): string {
    const canvasSize = this.extractCanvasSize(prompt);
    const derived = promptToGeneratorParams(prompt);
    const params = {
      width: canvasSize.width,
      height: canvasSize.height,
      resolution: 10,
      ...derived
    };
    return CellularAutomata.generate(params);
  }

  /**
   * Generate animated sketch
   *
   * @param prompt - The user prompt
   * @param context - Context for generation
   * @returns Animated sketch code
   */
  private static generateAnimatedSketch(prompt: string, context: string): string {
    const canvasSize = this.extractCanvasSize(prompt);
    const colors = this.extractColors(prompt);
    const seed = this.generateSeed(prompt, context);

    return `// Generated by Atelier P5Generator - Animated
// Prompt: ${prompt.substring(0, 100)}
// Seed: ${seed}

let t = 0;

function setup() {
  createCanvas(${canvasSize.width}, ${canvasSize.height});
  ${colors.background}
}

function draw() {
  ${colors.fill}

  t += 0.01;

  // Create flowing animation
  for (let x = 0; x < width; x += 20) {
    for (let y = 0; y < height; y += 20) {
      let d = dist(x, y, width / 2, height / 2);
      let offset = map(sin(t + d * 0.01), -1, 1, -10, 10);
      ellipse(x + offset, y + offset, 10, 10);
    }
  }
}`;
  }

  /**
   * Generate interactive sketch
   *
   * @param prompt - The user prompt
   * @param context - Context for generation
   * @returns Interactive sketch code
   */
  private static generateInteractiveSketch(prompt: string, context: string): string {
    const canvasSize = this.extractCanvasSize(prompt);
    const seed = this.generateSeed(prompt, context);

    return `// Generated by Atelier P5Generator - Interactive
// Prompt: ${prompt.substring(0, 100)}
// Seed: ${seed}

function setup() {
  createCanvas(${canvasSize.width}, ${canvasSize.height});
  background(220);
}

function draw() {
  // Draw follows mouse with trail effect
  if (mouseIsPressed) {
    fill(${seed % 255}, ${ (seed * 2) % 255}, ${ (seed * 3) % 255}, 50);
    noStroke();
    ellipse(mouseX, mouseY, 20, 20);
  }
}

function mousePressed() {
  background(random(255), random(255), random(255));
}

function mouseMoved() {
  fill(0, 0, 0, 10);
  ellipse(mouseX, mouseY, 5, 5);
}`;
  }

  /**
   * Extract canvas size from prompt
   *
   * @param prompt - The user prompt
   * @returns Object with width and height
   */
  private static extractCanvasSize(prompt: string): { width: number; height: number } {
    const sizeMatch = prompt.match(/(\d+)\s*[x×]\s*(\d+)/);
    if (sizeMatch) {
      return {
        width: parseInt(sizeMatch[1]) || 600,
        height: parseInt(sizeMatch[2]) || 400
      };
    }

    // Default canvas size
    const sizes = [
      { width: 600, height: 400 },
      { width: 800, height: 600 },
      { width: 400, height: 400 },
      { width: 1024, height: 768 }
    ];

    // Select based on prompt hash
    const index = Math.abs(hashCode(prompt)) % sizes.length;
    return sizes[index];
  }

  /**
   * Extract colors from prompt
   *
   * @param prompt - The user prompt
   * @returns Object with background and fill color code
   */
  private static extractColors(prompt: string): { background: string; fill: string } {
    const promptLower = prompt.toLowerCase();

    // Check for specific colors
    if (promptLower.includes('red')) {
      return {
        background: 'background(50);',
        fill: 'fill(255, 100, 100);'
      };
    } else if (promptLower.includes('blue')) {
      return {
        background: 'background(50);',
        fill: 'fill(100, 100, 255);'
      };
    } else if (promptLower.includes('green')) {
      return {
        background: 'background(50);',
        fill: 'fill(100, 255, 100);'
      };
    } else if (promptLower.includes('black') || promptLower.includes('dark')) {
      return {
        background: 'background(20);',
        fill: 'fill(255);'
      };
    } else {
      // Default colors
      return {
        background: 'background(220);',
        fill: 'fill(0);'
      };
    }
  }

  /**
   * Extract first number found in prompt
   *
   * @param prompt - The user prompt
   * @returns First number found or null
   */
  private static extractNumber(prompt: string): number | null {
    const match = prompt.match(/\d+/);
    return match ? parseInt(match[0]) : null;
  }

  /**
   * Generate seed from prompt and context
   *
   * @param prompt - The user prompt
   * @param context - Context string
   * @returns Numeric seed for variation
   */
  private static generateSeed(prompt: string, context: string): number {
    const randomFactor = Math.floor(Math.random() * 1000000);
    const combined = prompt + context + Date.now() + randomFactor;
    return Math.abs(hashCode(combined));
  }

}