import { hashCode } from '../../utils/hashCode.js';

/**
 * ParticleSystem - Specialized generator for p5.js particle systems
 *
 * Generates advanced particle system code with:
 * - Attraction/repulsion forces
 * - Decay and lifespan parameters
 * - Color mapping (velocity, position, age-based)
 * - Mouse interaction
 * - Various physics parameters
 *
 * Usage: ParticleSystem.generate({ particleCount: 100, attraction: true, decay: 0.95 })
 */
export class ParticleSystem {
  /**
   * Generate p5.js particle system code
   *
   * @param params - Configuration object for particle system
   * @returns Valid p5.js particle system code string
   */
  static generate(params: unknown = {}): string {
    const config = this.normalizeParams(params);

    return this.generateParticleSystemCode(config);
  }

  /**
   * Normalize and validate parameters
   *
   * @param params - Raw parameters (any type)
   * @returns Normalized configuration object
   */
  private static normalizeParams(params: unknown): ParticleSystemConfig {
    if (params === null || params === undefined) {
      return this.getDefaultConfig();
    }

    if (typeof params === 'object') {
      const obj = params as Record<string, unknown>;
      return {
        particleCount: this.getNumber(obj.particleCount, 100),
        attraction: Boolean(obj.attraction),
        attractionStrength: this.getNumber(obj.attractionStrength, 0.5),
        repulsion: Boolean(obj.repulsion),
        repulsionStrength: this.getNumber(obj.repulsionStrength, 0.5),
        decay: this.getNumber(obj.decay, 0.98),
        lifespan: this.getNumber(obj.lifespan, 255),
        colorMapping: this.getString(obj.colorMapping, 'velocity'),
        colors: this.getArray(obj.colors),
        mouseAttraction: Boolean(obj.mouseAttraction),
        width: this.getNumber(obj.width, 600),
        height: this.getNumber(obj.height, 400),
        palette: this.getString(obj.palette, 'default'),
        gravity: this.getNumber(obj.gravity, 0),
        friction: this.getNumber(obj.friction, 1),
        boundary: this.getString(obj.boundary, 'wrap'),
        trails: Boolean(obj.trails),
        minSize: this.getNumber(obj.minSize, 2),
        maxSize: this.getNumber(obj.maxSize, 8),
        speed: this.getNumber(obj.speed, 2),
        emissionRate: this.getNumber(obj.emissionRate, 0),
        colorMode: this.getString(obj.colorMode, 'RGB'),
        usePushMatrix: Boolean(obj.usePushMatrix),
        customEffect: this.getString(obj.customEffect, ''),
        description: this.getString(obj.description, ''),
        physics: obj.physics as Record<string, unknown> | undefined,
        visual: obj.visual as Record<string, unknown> | undefined
      };
    }

    return this.getDefaultConfig();
  }

  /**
   * Get number value with default
   */
  private static getNumber(value: unknown, defaultValue: number): number {
    if (typeof value === 'number' && !isNaN(value) && isFinite(value)) {
      return Math.max(0, value); // Ensure non-negative
    }
    return defaultValue;
  }

  /**
   * Get string value with default
   */
  private static getString(value: unknown, defaultValue: string): string {
    return typeof value === 'string' ? value : defaultValue;
  }

  /**
   * Get array value
   */
  private static getArray(value: unknown): string[] {
    if (Array.isArray(value)) {
      return value.map(String);
    }
    return [];
  }

  /**
   * Get default configuration
   */
  private static getDefaultConfig(): ParticleSystemConfig {
    return {
      particleCount: 100,
      attraction: false,
      attractionStrength: 0.5,
      repulsion: false,
      repulsionStrength: 0.5,
      decay: 0.98,
      lifespan: 255,
      colorMapping: 'velocity',
      colors: [],
      mouseAttraction: false,
      width: 600,
      height: 400,
      palette: 'default',
      gravity: 0,
      friction: 1,
      boundary: 'wrap',
      trails: false,
      minSize: 2,
      maxSize: 8,
      speed: 2,
      emissionRate: 0,
      colorMode: 'RGB',
      usePushMatrix: false,
      customEffect: '',
      description: '',
      physics: undefined,
      visual: undefined
    };
  }

  /**
   * Generate particle system code
   */
  private static generateParticleSystemCode(config: ParticleSystemConfig): string {
    const seed = this.generateSeed(config);
    const particleCount = Math.floor(config.particleCount);

    let code = `// Generated by Liminal ParticleSystem
// Particle Count: ${particleCount}
${config.description !== '' ? `// Description: ${config.description.substring(0, 100)}\n` : ''}
// Seed: ${seed}

let particles = [];

`;

    // Add color mode setup
    if (config.colorMode !== 'RGB') {
      code += `function setup() {
  createCanvas(${config.width}, ${config.height});
  colorMode(${config.colorMode});

  // Initialize particles
  for (let i = 0; i < ${particleCount}; i++) {
    particles.push(new Particle());
  }
}
`;
    } else {
      code += `function setup() {
  createCanvas(${config.width}, ${config.height});
  // RGB color mode
  colorMode(RGB);

  // Initialize particles
  for (let i = 0; i < ${particleCount}; i++) {
    particles.push(new Particle());
  }
}
`;
    }

    code += `
function draw() {
  ${this.generateBackground(config)}

  // Update and display particles
  for (let i = particles.length - 1; i >= 0; i--) {
    particles[i].update();
    particles[i].display();

    // Remove dead particles
    ${this.generateDeathCheck(config)}
  }

  ${this.generateEmission(config)}
}

class Particle {
  constructor() {
    this.x = random(width);
    this.y = random(height);
    this.vx = random(-${config.speed}, ${config.speed});
    this.vy = random(-${config.speed}, ${config.speed});
    this.size = random(${config.minSize}, ${config.maxSize});
    this.lifespan = ${config.lifespan};
    ${this.generateConstructorExtras(config)}
  }

  update() {
    ${this.generateForces(config)}

    // Apply velocity
    this.x += this.vx;
    this.y += this.vy;

    ${this.generateBoundaryBehavior(config)}

    // Apply decay
    this.lifespan *= ${config.decay};

    ${this.generateColorUpdate(config)}
  }

  display() {
    ${this.generateDisplay(config)}
  }

  ${this.generateHelperMethods(config)}
}
`;

    return code;
  }

  /**
   * Generate background code
   */
  private static generateBackground(config: ParticleSystemConfig): string {
    if (config.trails) {
      return `background(0, 0, 0, 20); // Trail effect`;
    }
    return `background(${this.getBackgroundColor(config)});`;
  }

  /**
   * Get background color based on palette
   */
  private static getBackgroundColor(config: ParticleSystemConfig): string {
    switch (config.palette) {
      case 'warm': return '30';
      case 'cool': return '20';
      case 'monochrome': return '128';
      default: return '0';
    }
  }

  /**
   * Generate particle death check
   */
  private static generateDeathCheck(config: ParticleSystemConfig): string {
    if (config.lifespan > 0) {
      return `if (particles[i].lifespan < 1) {
      particles.splice(i, 1);
    }`;
    }
    return '';
  }

  /**
   * Generate emission code
   */
  private static generateEmission(config: ParticleSystemConfig): string {
    if (config.emissionRate > 0) {
      return `// Emit new particles
  if (particles.length < ${config.particleCount * 2}) {
    for (let j = 0; j < ${config.emissionRate}; j++) {
      particles.push(new Particle());
    }
  }`;
    }
    return '';
  }

  /**
   * Generate constructor extras
   */
  private static generateConstructorExtras(config: ParticleSystemConfig): string {
    let extras = '';

    // Color initialization based on mapping
    const colorComment = this.getColorComment(config);
    if (config.colorMapping === 'velocity') {
      extras += `${colorComment}this.baseColor = color(${this.generateColor(config)});\n`;
    } else if (config.colorMapping === 'position') {
      extras += `${colorComment}this.baseColor = color(${this.generateColor(config)});\n`;
    } else if (config.colorMapping === 'age') {
      extras += `this.age = 0;\n`;
      extras += `${colorComment}this.baseColor = color(${this.generateColor(config)});\n`;
    } else {
      extras += `${colorComment}this.color = color(${this.generateColor(config)});\n`;
    }

    // Add custom effect
    if (config.customEffect) {
      extras += `// Custom effect: ${config.customEffect.substring(0, 50)}\n`;
    }

    return extras;
  }

  /**
   * Get color comment based on palette
   */
  private static getColorComment(config: ParticleSystemConfig): string {
    switch (config.palette) {
      case 'warm':
        return '// warm colors - red, orange, yellow\n';
      case 'cool':
        return '// cool colors - blue, cyan, purple\n';
      case 'monochrome':
        return '// monochrome grayscale\n';
      default:
        return '// RGB full spectrum\n';
    }
  }

  /**
   * Generate color values
   */
  private static generateColor(config: ParticleSystemConfig): string {
    if (config.colors.length > 0) {
      const colorIndex = Math.floor(Math.random() * config.colors.length);
      return config.colors[colorIndex];
    }

    switch (config.palette) {
      case 'warm':
        return `random(200, 255), random(50, 150), 50`;
      case 'cool':
        return `50, random(100, 200), random(200, 255)`;
      case 'monochrome':
        return `random(255)`;
      default:
        return `random(255), random(255), random(255)`;
    }
  }

  /**
   * Generate forces code
   */
  private static generateForces(config: ParticleSystemConfig): string {
    let forces = '';

    // Gravity
    if (config.gravity > 0) {
      forces += `// Gravity\n    this.vy += ${config.gravity};\n    `;
    }

    // Friction
    if (config.friction < 1) {
      forces += `// Friction\n    this.vx *= ${config.friction};\n    this.vy *= ${config.friction};\n    `;
    }

    // Attraction
    if (config.attraction) {
      forces += `// Attraction force\n    let attractX = width / 2;\n    `;
      forces += `let attractY = height / 2;\n    `;
      forces += `let dx = attractX - this.x;\n    `;
      forces += `let dy = attractY - this.y;\n    `;
      forces += `let dist = sqrt(dx * dx + dy * dy);\n    `;
      forces += `if (dist > 5) {\n    `;
      forces += `  let force = ${config.attractionStrength} / dist;\n    `;
      forces += `  this.vx += dx * force;\n    `;
      forces += `  this.vy += dy * force;\n    `;
      forces += `}\n    `;
    }

    // Repulsion
    if (config.repulsion) {
      forces += `// Repulsion force\n    let repelX = width / 2;\n    `;
      forces += `let repelY = height / 2;\n    `;
      forces += `let rdx = this.x - repelX;\n    `;
      forces += `let rdy = this.y - repelY;\n    `;
      forces += `let rdist = sqrt(rdx * rdx + rdy * rdy);\n    `;
      forces += `if (rdist < 100 && rdist > 5) {\n    `;
      forces += `  let rforce = ${config.repulsionStrength} / rdist;\n    `;
      forces += `  this.vx += rdx * rforce;\n    `;
      forces += `  this.vy += rdy * rforce;\n    `;
      forces += `}\n    `;
    }

    // Mouse attraction
    if (config.mouseAttraction) {
      forces += `// Mouse attraction\n    let mdx = mouseX - this.x;\n    `;
      forces += `let mdy = mouseY - this.y;\n    `;
      forces += `let mdist = sqrt(mdx * mdx + mdy * mdy);\n    `;
      forces += `if (mdist > 5) {\n    `;
      forces += `  let mforce = 0.5 / mdist;\n    `;
      forces += `  this.vx += mdx * mforce;\n    `;
      forces += `  this.vy += mdy * mforce;\n    `;
      forces += `}\n    `;
    }

    return forces;
  }

  /**
   * Generate boundary behavior
   */
  private static generateBoundaryBehavior(config: ParticleSystemConfig): string {
    switch (config.boundary) {
      case 'bounce':
        return `// Bounce off edges
    if (this.x < 0 || this.x > width) {
      this.vx *= -1;
      this.x = constrain(this.x, 0, width);
    }
    if (this.y < 0 || this.y > height) {
      this.vy *= -1;
      this.y = constrain(this.y, 0, height);
    }`;

      case 'wrap':
      default:
        return `// Wrap around edges
    if (this.x < 0) this.x = width;
    if (this.x > width) this.x = 0;
    if (this.y < 0) this.y = height;
    if (this.y > height) this.y = 0;`;
    }
  }

  /**
   * Generate color update code
   */
  private static generateColorUpdate(config: ParticleSystemConfig): string {
    switch (config.colorMapping) {
      case 'velocity':
        return `// Update color based on velocity
    let speed = sqrt(this.vx * this.vx + this.vy * this.vy);
    let colorRatio = constrain(speed / ${config.speed * 2}, 0, 1);
    this.color = lerpColor(
      color(255, 100, 100),
      color(100, 100, 255),
      colorRatio
    );`;

      case 'position':
        return `// Update color based on position
    let posX = this.x / width;
    let posY = this.y / height;
    this.color = color(
      posX * 255,
      posY * 255,
      150
    );`;

      case 'age':
        return `// Update color based on age
    this.age++;
    let ageRatio = this.age / ${config.lifespan};
    this.color = lerpColor(
      color(255, 255, 255),
      color(255, 100, 50),
      ageRatio
    );`;

      default:
        return '';
    }
  }

  /**
   * Generate display code
   */
  private static generateDisplay(config: ParticleSystemConfig): string {
    let display = '';

    if (config.usePushMatrix) {
      display += `push();\n    `;
    }

    display += `noStroke();\n    `;

    if (config.colorMapping !== 'none') {
      display += `fill(this.color, this.lifespan);\n    `;
    } else {
      display += `fill(this.color, this.lifespan);\n    `;
    }

    display += `ellipse(this.x, this.y, this.size);`;

    if (config.usePushMatrix) {
      display += `\n    pop();`;
    }

    return display;
  }

  /**
   * Generate helper methods
   */
  private static generateHelperMethods(config: ParticleSystemConfig): string {
    let helpers = '';

    if (config.attraction || config.repulsion) {
      helpers += `
  applyForce(fx, fy) {
    this.vx += fx;
    this.vy += fy;
  }
`;
    }

    if (config.physics || config.visual) {
      helpers += `
  // Custom physics/visual methods
  ${config.physics ? '// Physics customization enabled' : ''}
  ${config.visual ? '// Visual customization enabled' : ''}
`;
    }

    return helpers;
  }

  /**
   * Generate seed for variation
   */
  private static generateSeed(config: ParticleSystemConfig): number {
    const combined =
      config.particleCount +
      config.width +
      config.height +
      Date.now() +
      Math.random() * 1000000;
    return Math.abs(hashCode(combined.toString()));
  }

}

/**
 * Configuration interface for particle system
 */
interface ParticleSystemConfig {
  particleCount: number;
  attraction: boolean;
  attractionStrength: number;
  repulsion: boolean;
  repulsionStrength: number;
  decay: number;
  lifespan: number;
  colorMapping: string;
  colors: string[];
  mouseAttraction: boolean;
  width: number;
  height: number;
  palette: string;
  gravity: number;
  friction: number;
  boundary: string;
  trails: boolean;
  minSize: number;
  maxSize: number;
  speed: number;
  emissionRate: number;
  colorMode: string;
  usePushMatrix: boolean;
  customEffect: string;
  description: string;
  physics?: Record<string, unknown>;
  visual?: Record<string, unknown>;
}